# Docker image for springboot file run
# VERSION 0.0.1
# Author: Thomas
# 基础镜像使用java
FROM openjdk:17-jdk-buster
# 作者
MAINTAINER liuchen
# VOLUME 指定了临时文件目录为/tmp。
# 其效果是在主机 /var/lib/docker 目录下创建了一个临时文件，并链接到容器的/tmp
VOLUME /tmp
# 将jar包添加到容器中并更名为app.jar
ADD /target/ai-background-0.0.1-SNAPSHOT.jar background.jar

EXPOSE 8040
# 运行jar包
# touch命令，如果没有文件创建则创建文件，如果文件已存在，则修改时间戳
RUN bash -c 'touch /background.jar'
ENTRYPOINT ["java","-jar","/background.jar", "--env=8056ed5a-a62c-4aa2-aa9b-615bc6764eb3"]
